import { Geist, Geist_Mono } from "next/font/google";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import { HomePageProvider } from "./_provider/homeProvider";
import { AppSkeletonThemeProvider } from "./_provider/SkeletonThemeProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <HomePageProvider>
          <ThemeProvider attribute="class" enableSystem defaultTheme="system">
            <AppSkeletonThemeProvider>{children}</AppSkeletonThemeProvider>
          </ThemeProvider>
        </HomePageProvider>
      </body>
    </html>
  );
}
